# Google OAuth
spring.security.oauth2.client.registration.google.client-id=*
spring.security.oauth2.client.registration.google.client-secret=*

# Github OAuth
spring.security.oauth2.client.registration.github.client-id=test
spring.security.oauth2.client.registration.github.client-secret=test

# Cloudinary
cloudinary.api.key=test
cloudinary.api.secret=test
cloudinary.cloud.name=test

# Mail
app.domain-name=localhost:8081
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test@gmail.com
spring.mail.password=test123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.security.user.name=admin@gmail.com
spring.security.user.password=admin123