# ========================
# Google OAuth 2.0
# ========================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=email,profile

# ========================
# Github OAuth 2.0
# ========================
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:}
spring.security.oauth2.client.registration.github.scope=email,profile

# ========================
# Cloudinary
# ========================
cloudinary.api.key=${CLOUDINARY_API_KEY:}
cloudinary.api.secret=${CLOUDINARY_API_SECRET:}
cloudinary.cloud.name=${CLOUDINARY_NAME:}

# ========================
# Email Configuration
# ========================
spring.mail.host=${EMAIL_HOST:}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.username=${EMAIL_USERNAME:}
spring.mail.password=${EMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ========================
# Custom App Property
# ========================
app.domain-name=${EMAIL_DOMAIN:http://localhost:8081}